import {faker} from "@faker-js/faker";
import {Chapter} from "src/app/_models/chapter";
import {AgeRating} from "src/app/_models/metadata/age-rating";

export class ChapterBuilder {
  private chapter: Partial<Chapter> = {
    id: 0,
    range: "-100000",
    number: "-100000",
    minNumber: -100000,
    maxNumber: -100000,
    files: [],
    coverImage: "cover.png",
    coverImageLocked: false,
    pages: 0,
    volumeId: 0,
    pagesRead: 0,
    isSpecial: false,
    title: "Book -100000",
    createdUtc: new Date().toISOString(),
    titleName: faker.book.title(),
    summary: faker.lorem.paragraph(),
    minHoursToRead: 1,
    maxHoursToRead: 999,
    avgHoursToRead: 666,
    ageRating: AgeRating.Everyone,
    releaseDate: "",
    wordCount: 45083,
    volumeTitle: "Testing, the Beginning",
    webLinks: "",
    isbn: "",
    lastReadingProgress: "",
    sortOrder: -10000,
    primaryColor: "#3E41FF",
    secondaryColor: "#FB513D",
    year: "1988",
    language: mockEpubSeriesMetadata.language,
    publicationStatus: PublicationStatus.Completed,
    count: 1,
    totalCount: 0,
    genres: [],
    tags: [
    ],
    writers: [
    ],
    coverArtists: [],
    ],
    characters: [],
    pencillers: [],
    inkers: [],
    imprints: [],
    colorists: [],
    letterers: [],
    editors: [],
    translators: [],
    teams: [],
    locations: [],
    summaryLocked: false,
    genresLocked: false,
    tagsLocked: false,
    writerLocked: false,
    coverArtistLocked: false,
    publisherLocked: false,
    characterLocked: false,
    pencillerLocked: false,
    inkerLocked: false,
    imprintLocked: false,
    coloristLocked: false,
    lettererLocked: false,
    editorLocked: false,
    translatorLocked: false,
    teamLocked: false,
    locationLocked: false,
    ageRatingLocked: false,
    languageLocked: false,
    isbnLocked: false,
    titleNameLocked: false,
    sortOrderLocked: false,
    releaseDateLocked: false
  }
}
